name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [22.x, 23.x, 24.x]
        elixir: [1.11.x, 1.12.x]

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: erlef/setup-elixir@v1.10
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: |
            deps
            _build/dev
            _build/test
          key: elixir-cache-5goNLzIDwagspnM2-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            elixir-cache-5goNLzIDwagspnM2-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-
            elixir-cache-5goNLzIDwagspnM2-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Coveralls
        env:
          MIX_ENV: test
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BINANCE_API_SPOT_DOMAIN: testnet.binance.vision
          BINANCE_API_USD_MARGIN_FUTURES_DOMAIN: testnet.binancefuture.com
          BINANCE_API_COIN_MARGIN_FUTURES_DOMAIN: testnet.binancefuture.com
          BINANCE_API_KEY: abc123
          BINANCE_API_SECRET: abc123
        run: mix coveralls.github
