name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [22.x, 23.x, 24.x]
        elixir: [1.10.x, 1.11.x, 1.12.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: erlef/setup-elixir@v1.7.1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      # - name: Cache Dependencies
      #   uses: actions/cache@v2.1.6
      #   with:
      #     path: |
      #       deps
      #       _build/dev
      #       _build/test
      #     key: elixir-cache-5goNLzIDwagspnM2-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
      #     restore-keys: |
      #       elixir-cache-5goNLzIDwagspnM2-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-
      #       elixir-cache-5goNLzIDwagspnM2-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Test
        env:
          BINANCE_API_DOMAIN: testnet.binance.vision
          BINANCE_API_KEY: abc123
          BINANCE_API_SECRET: abc123
        run: mix test

      - name: Dialyzer
        run: mix dialyzer
